### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by webdesus** [webdesus/polymer-ide.vim#13]
initiated @aemonge.

![](https://user-images.githubusercontent.com/1322348/27362713-e03c62e2-55f5-11e7-892f-a08c88216160.png)

![](https://user-images.githubusercontent.com/1322348/27362711-ddee7ef8-55f5-11e7-86ab-092bc7cca637.png)

**Comment by webdesus** [comment]
@aemonge сan i ask a couple questions

1. What OS you use.
2. If you open local file polylint.vim, you see excess symbols(^M)?

If you have opportunity, create new empty .vim file. Where will be only my plugin and symantics without settings. For test.

**Comment by aemonge** [comment]
Hi @webdesus ,

Sorry for my delayed answer. I'm on a **MacOS Sierra 10.12.5**, and I've also checked the _polylin.vim_ file and I don't see any (^M) symbols; so I don't think the issue is related with break lines from windows.

I've removed all of my plugins expect Vundle, YCM and yours. And this is the output I'm getting:

<img width="1440" alt="screen shot 2017-06-27 at 7 30 45 pm" src="https://user-images.githubusercontent.com/1322348/27615626-43c8de48-5b6f-11e7-9f3a-9aa40e8ecf2d.png">
<img width="1440" alt="screen shot 2017-06-27 at 7 31 15 pm" src="https://user-images.githubusercontent.com/1322348/27615625-43c20ea6-5b6f-11e7-8b5b-3a5c71230ad4.png">

How else can I help ?

**Comment by webdesus** [comment]
Stupid question, but i should asked "do you make `npm install` when use empty vim file?"

**Comment by webdesus** [comment]
In new version 0.4.4 I add error message when user forgot execute `npm install` command. Try agin)

**Comment by JpOnline** [comment]
I'm having the same issue, running `npm install` but getting similar error messages anyway. I'm using macVim in MacOS Yosemite 10.10.5

**Comment by webdesus** [comment]
I'll try to find a mac in the near future...

**Comment by webdesus** [comment]
Fixed, should work now.( version 0.4.5)
